numThreads=1

topicIn=topic_cdrs


#topicOut=topic_out

brokers=127.0.0.1:9092

applicationID=cdrs-kafka-streams-v0

pathOutFiles=.
nameOutFiles=test-files
recordsOutFiles=1000000


bulk.hosts=127.0.0.1:9200
bulk.user=
bulk.passwd=
bulk.threads=2
bulk.seconds=60
bulk.bytes=500000
bulk.batch=500

%errores=2

